-  name: install java
   yum:
     name: java
     state: installed

-  name: install maven
   yum:
     name: maven
     state: installed

-  name: install httpd
   yum:
     name: httpd
     state: installed
     
-  name: start web server
   service:
     name: httpd
     state: started
